---
driver:
  name: vagrant
  vagrantfiles:
  - VagrantAdditionalConfig.rb
provisioner:
  name: chef_zero
  always_update_cookbooks: true
  chef_omnibus_install_options: -d /tmp/vagrant-cache/vagrant_omnibus
  require_chef_omnibus: 12.10.24
verifier:
  name: inspec
platforms:
- name: ubuntu-16.04
- name: centos-7.2
suites:
- name: default
  run_list:
  - recipe[curl-windows::default]
  verifier:
    inspec_tests:
    - test/recipes
  attributes:
